/**
 * Tests generated by Claude
 */
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { setActivePinia, createPinia } from 'pinia'

// Import mocks FIRST
import {
  mockWalletNamed,
  mockTestNetWalletNamed,
  mockMainnetWallet,
  mockChipnetWallet,
  localStorageMock,
  mockGetAllWalletsWithNetworkInfo,
  mockDeleteWalletFromDb,
} from './mocks/store.mocks'

// Import store after mocks
import { useStore } from '../src/stores/store'

describe('switchWallet', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    localStorageMock.clear()
    // Create fresh Pinia instance for each test
    setActivePinia(createPinia())
  })

  describe('wallet loading', () => {
    it('loads mainnet wallet when network is mainnet', async () => {
      localStorageMock.setItem('network', 'mainnet')
      mockWalletNamed.mockResolvedValue(mockMainnetWallet)

      const store = useStore()
      // Set initial wallet to avoid "No wallet set" error
      store.setWallet(mockMainnetWallet as never)

      await store.switchWallet('newWallet')

      expect(mockWalletNamed).toHaveBeenCalledWith('newWallet')
      expect(mockTestNetWalletNamed).not.toHaveBeenCalled()
    })

    it('loads chipnet wallet when network is chipnet', async () => {
      localStorageMock.setItem('network', 'chipnet')
      mockTestNetWalletNamed.mockResolvedValue(mockChipnetWallet)

      const store = useStore()
      store.setWallet(mockChipnetWallet as never)

      await store.switchWallet('newWallet')

      expect(mockTestNetWalletNamed).toHaveBeenCalledWith('newWallet')
      expect(mockWalletNamed).not.toHaveBeenCalled()
    })

    it('defaults to mainnet when no network in localStorage', async () => {
      // No network set in localStorage
      mockWalletNamed.mockResolvedValue(mockMainnetWallet)

      const store = useStore()
      store.setWallet(mockMainnetWallet as never)

      await store.switchWallet('newWallet')

      expect(mockWalletNamed).toHaveBeenCalledWith('newWallet')
    })
  })

  describe('state updates', () => {
    beforeEach(() => {
      localStorageMock.setItem('network', 'mainnet')
      mockWalletNamed.mockResolvedValue(mockMainnetWallet)
    })

    it('updates activeWalletName in store', async () => {
      const store = useStore()
      store.setWallet(mockMainnetWallet as never)

      await store.switchWallet('differentWallet')

      expect(store.activeWalletName).toBe('differentWallet')
    })

    it('persists activeWalletName to localStorage', async () => {
      const store = useStore()
      store.setWallet(mockMainnetWallet as never)

      await store.switchWallet('persistedWallet')

      expect(localStorageMock.setItem).toHaveBeenCalledWith('activeWalletName', 'persistedWallet')
    })

    it('sets _wallet to mainnet wallet instance', async () => {
      const store = useStore()
      store.setWallet(mockMainnetWallet as never)

      await store.switchWallet('newWallet')

      // Verify wallet was set by checking its properties
      expect(store._wallet?.network).toBe('mainnet')
      expect(store._wallet?.cashaddr).toBe(mockMainnetWallet.cashaddr)
    })

    it('sets _wallet to chipnet wallet instance', async () => {
      localStorageMock.setItem('network', 'chipnet')
      mockTestNetWalletNamed.mockResolvedValue(mockChipnetWallet)
      const store = useStore()
      store.setWallet(mockMainnetWallet as never)

      await store.switchWallet('newWallet')

      // Verify chipnet wallet was set by checking its properties
      expect(store._wallet?.network).toBe('chipnet')
      expect(store._wallet?.cashaddr).toBe(mockChipnetWallet.cashaddr)
    })
  })

  describe('error handling', () => {
    it('throws when wallet loading fails', async () => {
      localStorageMock.setItem('network', 'mainnet')
      mockWalletNamed.mockRejectedValue(new Error('Wallet not found'))

      const store = useStore()
      store.setWallet(mockMainnetWallet as never)

      await expect(store.switchWallet('nonexistentWallet')).rejects.toThrowError()
    })

    it('does not mutate state when wallet loading fails', async () => {
      localStorageMock.setItem('network', 'mainnet')
      localStorageMock.setItem('activeWalletName', 'originalWallet')
      localStorageMock.setItem.mockClear()
      mockWalletNamed.mockRejectedValue(new Error('Wallet not found'))

      const store = useStore()
      store.setWallet(mockMainnetWallet as never)
      store.activeWalletName = 'originalWallet'
      store.displayView = 5
      const originalWalletRef = store._wallet

      try {
        await store.switchWallet('failedWallet')
      } catch {
        // Expected to throw
      }

      // No state should be mutated on failure
      expect(store.activeWalletName).toBe('originalWallet')
      expect(store._wallet).toBe(originalWalletRef)
      expect(store.displayView).toBe(5)
      expect(localStorageMock.setItem).not.toHaveBeenCalledWith('activeWalletName', 'failedWallet')
    })
  })
})

describe('deleteWallet', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    localStorageMock.clear()
    setActivePinia(createPinia())
    mockGetAllWalletsWithNetworkInfo.mockResolvedValue([])
  })

  it('throws when trying to delete the active wallet', async () => {
    const store = useStore()
    store.setWallet(mockMainnetWallet as never)
    // activeWalletName defaults to 'mywallet'

    await expect(store.deleteWallet('mywallet')).rejects.toThrowError()
  })

  it('does not call deleteWalletFromDb when trying to delete active wallet', async () => {
    const store = useStore()
    store.setWallet(mockMainnetWallet as never)

    try {
      await store.deleteWallet('mywallet')
    } catch {
      // Expected to throw
    }

    expect(mockDeleteWalletFromDb).not.toHaveBeenCalled()
  })

  it('deletes wallet from both mainnet and testnet databases', async () => {
    const store = useStore()
    store.setWallet(mockMainnetWallet as never)

    await store.deleteWallet('otherWallet')

    expect(mockDeleteWalletFromDb).toHaveBeenCalledWith('otherWallet', 'bitcoincash')
    expect(mockDeleteWalletFromDb).toHaveBeenCalledWith('otherWallet', 'bchtest')
    expect(mockDeleteWalletFromDb).toHaveBeenCalledTimes(2)
  })

  it('refreshes available wallets after deletion', async () => {
    const store = useStore()
    store.setWallet(mockMainnetWallet as never)

    await store.deleteWallet('otherWallet')

    expect(mockGetAllWalletsWithNetworkInfo).toHaveBeenCalled()
  })

  it('propagates error if mainnet deletion fails (testnet not attempted)', async () => {
    mockDeleteWalletFromDb.mockRejectedValueOnce(new Error('DB error'))
    const store = useStore()
    store.setWallet(mockMainnetWallet as never)

    await expect(store.deleteWallet('otherWallet')).rejects.toThrowError()

    // Only mainnet deletion was attempted before failure
    expect(mockDeleteWalletFromDb).toHaveBeenCalledTimes(1)
    expect(mockDeleteWalletFromDb).toHaveBeenCalledWith('otherWallet', 'bitcoincash')
    // Wallet list not refreshed on failure
    expect(mockGetAllWalletsWithNetworkInfo).not.toHaveBeenCalled()
  })

  it('propagates error if testnet deletion fails (mainnet already deleted)', async () => {
    mockDeleteWalletFromDb
      .mockResolvedValueOnce(undefined) // mainnet succeeds
      .mockRejectedValueOnce(new Error('DB error')) // testnet fails
    const store = useStore()
    store.setWallet(mockMainnetWallet as never)

    await expect(store.deleteWallet('otherWallet')).rejects.toThrowError()

    // Both deletions were attempted
    expect(mockDeleteWalletFromDb).toHaveBeenCalledTimes(2)
    // Wallet list not refreshed on failure
    expect(mockGetAllWalletsWithNetworkInfo).not.toHaveBeenCalled()
  })
})
