# This file exists to force pnpm to install deps here, isolated from the root workspace.
# Quasar installs these when building/running the capacitor mode.
# https://quasar.dev/quasar-cli-vite/upgrade-guide#pnpm-related

# Migrated from package.json "resolutions".
overrides:
  tar: 7.5.16

allowBuilds:
